inherit_from: .rubocop_todo.yml
require: rubocop-minitest

AllCops:
  Exclude:
    - lib/generators/deploy_pin/**/templates/**/*.rb
  NewCops: disable
  TargetRubyVersion: 3.1

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - test/**/*_test.rb
